// Top clubs from major leagues
export const clubs = [
  // Premier League (England)
  { name: 'Arsenal', league: 'Premier League', country: 'England' },
  { name: 'Aston Villa', league: 'Premier League', country: 'England' },
  { name: 'Bournemouth', league: 'Premier League', country: 'England' },
  { name: 'Brentford', league: 'Premier League', country: 'England' },
  { name: 'Brighton & Hove Albion', league: 'Premier League', country: 'England' },
  { name: 'Chelsea', league: 'Premier League', country: 'England' },
  { name: 'Crystal Palace', league: 'Premier League', country: 'England' },
  { name: 'Everton', league: 'Premier League', country: 'England' },
  { name: 'Fulham', league: 'Premier League', country: 'England' },
  { name: 'Ipswich Town', league: 'Premier League', country: 'England' },
  { name: 'Leicester City', league: 'Premier League', country: 'England' },
  { name: 'Liverpool', league: 'Premier League', country: 'England' },
  { name: 'Manchester City', league: 'Premier League', country: 'England' },
  { name: 'Manchester United', league: 'Premier League', country: 'England' },
  { name: 'Newcastle United', league: 'Premier League', country: 'England' },
  { name: 'Nottingham Forest', league: 'Premier League', country: 'England' },
  { name: 'Southampton', league: 'Premier League', country: 'England' },
  { name: 'Tottenham Hotspur', league: 'Premier League', country: 'England' },
  { name: 'West Ham', league: 'Premier League', country: 'England' },
  { name: 'Wolverhampton', league: 'Premier League', country: 'England' },

  // La Liga (Spain)
  { name: 'Alavés', league: 'La Liga', country: 'Spain' },
  { name: 'Athletic Bilbao', league: 'La Liga', country: 'Spain' },
  { name: 'Atlético Madrid', league: 'La Liga', country: 'Spain' },
  { name: 'Barcelona', league: 'La Liga', country: 'Spain' },
  { name: 'Celta Vigo', league: 'La Liga', country: 'Spain' },
  { name: 'Espanyol', league: 'La Liga', country: 'Spain' },
  { name: 'Getafe', league: 'La Liga', country: 'Spain' },
  { name: 'Las Palmas', league: 'La Liga', country: 'Spain' },
  { name: 'Leganés', league: 'La Liga', country: 'Spain' },
  { name: 'Mallorca', league: 'La Liga', country: 'Spain' },
  { name: 'Osasuna', league: 'La Liga', country: 'Spain' },
  { name: 'Rayo Vallecano', league: 'La Liga', country: 'Spain' },
  { name: 'Real Betis', league: 'La Liga', country: 'Spain' },
  { name: 'Real Madrid', league: 'La Liga', country: 'Spain' },
  { name: 'Real Sociedad', league: 'La Liga', country: 'Spain' },
  { name: 'Sevilla', league: 'La Liga', country: 'Spain' },
  { name: 'Girona', league: 'La Liga', country: 'Spain' },
  { name: 'Valencia', league: 'La Liga', country: 'Spain' },
  { name: 'Valladolid', league: 'La Liga', country: 'Spain' },
  { name: 'Villareal', league: 'La Liga', country: 'Spain' },

  // Serie A (Italy)
  { name: 'Atalanta', league: 'Serie A', country: 'Italy' },
  { name: 'Bologna', league: 'Serie A', country: 'Italy' },
  { name: 'Cagliari', league: 'Serie A', country: 'Italy' },
  { name: 'Como', league: 'Serie A', country: 'Italy' },
  { name: 'Empoli', league: 'Serie A', country: 'Italy' },
  { name: 'Fiorentina', league: 'Serie A', country: 'Italy' },
  { name: 'Genoa', league: 'Serie A', country: 'Italy' },
  { name: 'Hellas Verona', league: 'Serie A', country: 'Italy' },
  { name: 'Juventus', league: 'Serie A', country: 'Italy' },
  { name: 'Lecce', league: 'Serie A', country: 'Italy' },
  { name: 'Napoli', league: 'Serie A', country: 'Italy' },
  { name: 'Parma', league: 'Serie A', country: 'Italy' },
  { name: 'Roma', league: 'Serie A', country: 'Italy' },
  { name: 'Torino', league: 'Serie A', country: 'Italy' },
  { name: 'Udinese', league: 'Serie A', country: 'Italy' },
  { name: 'Venezia', league: 'Serie A', country: 'Italy' },
  { name: 'Inter', league: 'Serie A', country: 'Italy' },
  { name: 'Milan', league: 'Serie A', country: 'Italy' },
  { name: 'Lazio', league: 'Serie A', country: 'Italy' },
  { name: 'AC Monza', league: 'Serie A', country: 'Italy' },

  // Ligue 1 (France)
  { name: 'Angers SCO', league: 'Ligue 1', country: 'France' },
  { name: 'AS Saint-Étienne', league: 'Ligue 1', country: 'France' },
  { name: 'AS Monaco', league: 'Ligue 1', country: 'France' },
  { name: 'Auxerre', league: 'Ligue 1', country: 'France' },
  { name: 'Havre AC', league: 'Ligue 1', country: 'France' },
  { name: 'LOSC Lille', league: 'Ligue 1', country: 'France' },
  { name: 'Montpellier HSC', league: 'Ligue 1', country: 'France' },
  { name: 'OGC Nice', league: 'Ligue 1', country: 'France' },
  { name: 'Olympique de Marseille', league: 'Ligue 1', country: 'France' },
  { name: 'FC Nantes', league: 'Ligue 1', country: 'France' },
  { name: 'Olympique Lyonnais', league: 'Ligue 1', country: 'France' },
  { name: 'Paris Saint-Germain', league: 'Ligue 1', country: 'France' },
  { name: 'Racing Club de Lens', league: 'Ligue 1', country: 'France' },
  { name: 'RC Strasbourg Alsace', league: 'Ligue 1', country: 'France' },
  { name: 'Stade Brestois 29', league: 'Ligue 1', country: 'France' },
  { name: 'Stade de Reims', league: 'Ligue 1', country: 'France' },
  { name: 'Stade Rennais FC', league: 'Ligue 1', country: 'France' },
  { name: 'Toulouse FC', league: 'Ligue 1', country: 'France' },

  // Bundesliga (Germany)
  { name: 'Bayern Munich', league: 'Bundesliga', country: 'Germany' },
  { name: 'Borussia Dortmund', league: 'Bundesliga', country: 'Germany' },
  { name: 'RB Leipzig', league: 'Bundesliga', country: 'Germany' },
  { name: 'Bayer Leverkusen', league: 'Bundesliga', country: 'Germany' },
  { name: 'Union Berlin', league: 'Bundesliga', country: 'Germany' },
  { name: 'Freiburg', league: 'Bundesliga', country: 'Germany' },
  { name: 'Eintracht Frankfurt', league: 'Bundesliga', country: 'Germany' },
  { name: 'VfL Wolfsburg', league: 'Bundesliga', country: 'Germany' },
  { name: 'Borussia Mönchengladbach', league: 'Bundesliga', country: 'Germany' },
  { name: 'Mainz 05', league: 'Bundesliga', country: 'Germany' },
  { name: 'Werder Bremen', league: 'Bundesliga', country: 'Germany' },
  { name: 'Hoffenheim', league: 'Bundesliga', country: 'Germany' },
  { name: 'Augsburg', league: 'Bundesliga', country: 'Germany' },
  { name: 'VfB Stuttgart', league: 'Bundesliga', country: 'Germany' },
  { name: 'Bochum', league: 'Bundesliga', country: 'Germany' },
  { name: 'Heidenheim', league: 'Bundesliga', country: 'Germany' },
  { name: 'Darmstadt 98', league: 'Bundesliga', country: 'Germany' },

  // Eredivisie (Netherlands)
  { name: 'Ajax', league: 'Eredivisie', country: 'Netherlands' },
  { name: 'PSV Eindhoven', league: 'Eredivisie', country: 'Netherlands' },
  { name: 'Feyenoord', league: 'Eredivisie', country: 'Netherlands' },
  { name: 'AZ Alkmaar', league: 'Eredivisie', country: 'Netherlands' },
  { name: 'Twente', league: 'Eredivisie', country: 'Netherlands' },
  { name: 'Utrecht', league: 'Eredivisie', country: 'Netherlands' },
  { name: 'Vitesse', league: 'Eredivisie', country: 'Netherlands' },
  { name: 'Heerenveen', league: 'Eredivisie', country: 'Netherlands' },
  { name: 'Groningen', league: 'Eredivisie', country: 'Netherlands' },
  { name: 'Sparta Rotterdam', league: 'Eredivisie', country: 'Netherlands' },
  { name: 'Go Ahead Eagles', league: 'Eredivisie', country: 'Netherlands' },
  { name: 'NEC Nijmegen', league: 'Eredivisie', country: 'Netherlands' },

  // Primeira Liga (Portugal)
  { name: 'Benfica', league: 'Primeira Liga', country: 'Portugal' },
  { name: 'Porto', league: 'Primeira Liga', country: 'Portugal' },
  { name: 'Sporting CP', league: 'Primeira Liga', country: 'Portugal' },
  { name: 'Braga', league: 'Primeira Liga', country: 'Portugal' },
  { name: 'Vitória de Guimarães', league: 'Primeira Liga', country: 'Portugal' },
  { name: 'Boavista', league: 'Primeira Liga', country: 'Portugal' },
  { name: 'Famalicão', league: 'Primeira Liga', country: 'Portugal' },
  { name: 'Arouca', league: 'Primeira Liga', country: 'Portugal' },
  { name: 'Estoril Praia', league: 'Primeira Liga', country: 'Portugal' },
  { name: 'Rio Ave', league: 'Primeira Liga', country: 'Portugal' },
  { name: 'Paços de Ferreira', league: 'Primeira Liga', country: 'Portugal' },
  { name: 'Chaves', league: 'Primeira Liga', country: 'Portugal' },

  // Scottish Premiership (Scotland)
  { name: 'Celtic', league: 'Scottish Premiership', country: 'Scotland' },
  { name: 'Rangers', league: 'Scottish Premiership', country: 'Scotland' },
  { name: 'Hearts', league: 'Scottish Premiership', country: 'Scotland' },
  { name: 'Hibernian', league: 'Scottish Premiership', country: 'Scotland' },
  { name: 'Aberdeen', league: 'Scottish Premiership', country: 'Scotland' },
  { name: 'St Mirren', league: 'Scottish Premiership', country: 'Scotland' },
  { name: 'Motherwell', league: 'Scottish Premiership', country: 'Scotland' },
  { name: 'Livingston', league: 'Scottish Premiership', country: 'Scotland' },
  { name: 'Ross County', league: 'Scottish Premiership', country: 'Scotland' },
  { name: 'Dundee United', league: 'Scottish Premiership', country: 'Scotland' },
  { name: 'Kilmarnock', league: 'Scottish Premiership', country: 'Scotland' },
  { name: 'St Johnstone', league: 'Scottish Premiership', country: 'Scotland' },

  // MLS (USA)
  { name: 'Atlanta United', league: 'MLS', country: 'USA' },
  { name: 'Austin FC', league: 'MLS', country: 'USA' },
  { name: 'Charlotte FC', league: 'MLS', country: 'USA' },
  { name: 'Chicago Fire', league: 'MLS', country: 'USA' },
  { name: 'FC Cincinnati', league: 'MLS', country: 'USA' },
  { name: 'Colorado Rapids', league: 'MLS', country: 'USA' },
  { name: 'Columbus Crew', league: 'MLS', country: 'USA' },
  { name: 'D.C. United', league: 'MLS', country: 'USA' },
  { name: 'FC Dallas', league: 'MLS', country: 'USA' },
  { name: 'Houston Dynamo', league: 'MLS', country: 'USA' },
  { name: 'Inter Miami', league: 'MLS', country: 'USA' },
  { name: 'LA Galaxy', league: 'MLS', country: 'USA' },
  { name: 'Los Angeles FC', league: 'MLS', country: 'USA' },
  { name: 'Minnesota United', league: 'MLS', country: 'USA' },
  { name: 'CF Montréal', league: 'MLS', country: 'USA' },
  { name: 'Nashville SC', league: 'MLS', country: 'USA' },
  { name: 'New England Revolution', league: 'MLS', country: 'USA' },
  { name: 'New York City FC', league: 'MLS', country: 'USA' },
  { name: 'New York Red Bulls', league: 'MLS', country: 'USA' },
  
];
export const leagues = Array.from(new Set(clubs.map(club => club.league)));