// Top clubs from major leagues
export const clubs = [
  // Premier League (England)
  { name: 'Arsenal', league: 'Premier League', country: 'England' },
  { name: 'Aston Villa', league: 'Premier League', country: 'England' },
  { name: 'Bournemouth', league: 'Premier League', country: 'England' },
  { name: 'Brentford', league: 'Premier League', country: 'England' },
  { name: 'Brighton & Hove Albion', league: 'Premier League', country: 'England' },
  { name: 'Chelsea', league: 'Premier League', country: 'England' },
  { name: 'Crystal Palace', league: 'Premier League', country: 'England' },
  { name: 'Everton', league: 'Premier League', country: 'England' },
  { name: 'Fulham', league: 'Premier League', country: 'England' },
  { name: 'Ipswich Town', league: 'Premier League', country: 'England' },
  { name: 'Leicester City', league: 'Premier League', country: 'England' },
  { name: 'Liverpool', league: 'Premier League', country: 'England' },
  { name: 'Manchester City', league: 'Premier League', country: 'England' },
  { name: 'Manchester United', league: 'Premier League', country: 'England' },
  { name: 'Newcastle United', league: 'Premier League', country: 'England' },
  { name: 'Nottingham Forest', league: 'Premier League', country: 'England' },
  { name: 'Southampton', league: 'Premier League', country: 'England' },
  { name: 'Tottenham Hotspur', league: 'Premier League', country: 'England' },
  { name: 'West Ham', league: 'Premier League', country: 'England' },
  { name: 'Wolverhampton', league: 'Premier League', country: 'England' },

  // La Liga (Spain)
  { name: 'Alavés', league: 'La Liga', country: 'Spain' },
  { name: 'Athletic Bilbao', league: 'La Liga', country: 'Spain' },
  { name: 'Atlético Madrid', league: 'La Liga', country: 'Spain' },
  { name: 'Barcelona', league: 'La Liga', country: 'Spain' },
  { name: 'Celta Vigo', league: 'La Liga', country: 'Spain' },
  { name: 'Espanyol', league: 'La Liga', country: 'Spain' },
  { name: 'Getafe', league: 'La Liga', country: 'Spain' },
  { name: 'Las Palmas', league: 'La Liga', country: 'Spain' },
  { name: 'Leganés', league: 'La Liga', country: 'Spain' },
  { name: 'Mallorca', league: 'La Liga', country: 'Spain' },
  { name: 'Osasuna', league: 'La Liga', country: 'Spain' },
  { name: 'Rayo Vallecano', league: 'La Liga', country: 'Spain' },
  { name: 'Real Betis', league: 'La Liga', country: 'Spain' },
  { name: 'Real Madrid', league: 'La Liga', country: 'Spain' },
  { name: 'Real Sociedad', league: 'La Liga', country: 'Spain' },
  { name: 'Sevilla', league: 'La Liga', country: 'Spain' },
  { name: 'Girona', league: 'La Liga', country: 'Spain' },
  { name: 'Valencia', league: 'La Liga', country: 'Spain' },
  { name: 'Valladolid', league: 'La Liga', country: 'Spain' },
  { name: 'Villareal', league: 'La Liga', country: 'Spain' },

  // Serie A (Italy)
  { name: 'Atalanta', league: 'Serie A', country: 'Italy' },
  { name: 'Bologna', league: 'Serie A', country: 'Italy' },
  { name: 'Cagliari', league: 'Serie A', country: 'Italy' },
  { name: 'Como', league: 'Serie A', country: 'Italy' },
  { name: 'Empoli', league: 'Serie A', country: 'Italy' },
  { name: 'Fiorentina', league: 'Serie A', country: 'Italy' },
  { name: 'Genoa', league: 'Serie A', country: 'Italy' },
  { name: 'Hellas Verona', league: 'Serie A', country: 'Italy' },
  { name: 'Juventus', league: 'Serie A', country: 'Italy' },
  { name: 'Lecce', league: 'Serie A', country: 'Italy' },
  { name: 'Napoli', league: 'Serie A', country: 'Italy' },
  { name: 'Parma', league: 'Serie A', country: 'Italy' },
  { name: 'Roma', league: 'Serie A', country: 'Italy' },
  { name: 'Torino', league: 'Serie A', country: 'Italy' },
  { name: 'Udinese', league: 'Serie A', country: 'Italy' },
  { name: 'Venezia', league: 'Serie A', country: 'Italy' },
  { name: 'Inter', league: 'Serie A', country: 'Italy' },
  { name: 'Milan', league: 'Serie A', country: 'Italy' },
  { name: 'Lazio', league: 'Serie A', country: 'Italy' },
  { name: 'AC Monza', league: 'Serie A', country: 'Italy' },

  // Ligue 1 (France)
  { name: 'Angers SCO', league: 'Ligue 1', country: 'France' },
  { name: 'AS Saint-Étienne', league: 'Ligue 1', country: 'France' },
  { name: 'AS Monaco', league: 'Ligue 1', country: 'France' },
  { name: 'Auxerre', league: 'Ligue 1', country: 'France' },
  { name: 'Havre AC', league: 'Ligue 1', country: 'France' },
  { name: 'LOSC Lille', league: 'Ligue 1', country: 'France' },
  { name: 'Montpellier HSC', league: 'Ligue 1', country: 'France' },
  { name: 'OGC Nice', league: 'Ligue 1', country: 'France' },
  { name: 'Olympique de Marseille', league: 'Ligue 1', country: 'France' },
  { name: 'FC Nantes', league: 'Ligue 1', country: 'France' },
  { name: 'Olympique Lyonnais', league: 'Ligue 1', country: 'France' },
  { name: 'Paris Saint-Germain', league: 'Ligue 1', country: 'France' },
  { name: 'Racing Club de Lens', league: 'Ligue 1', country: 'France' },
  { name: 'RC Strasbourg Alsace', league: 'Ligue 1', country: 'France' },
  { name: 'Stade Brestois 29', league: 'Ligue 1', country: 'France' },
  { name: 'Stade de Reims', league: 'Ligue 1', country: 'France' },
  { name: 'Stade Rennais FC', league: 'Ligue 1', country: 'France' },
  { name: 'Toulouse FC', league: 'Ligue 1', country: 'France' },
];
export const leagues = Array.from(new Set(clubs.map(club => club.league)));